# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23f883ce6f99fffde676c20a73386c02641517d283b6d271a06921e309cad06c5f1df10fdc8ab11d9dd891cca5397c50a8deb51514a8822fde7e44b25d902669

test:
  secret_key_base: 4619bc6e93c6c774cddc31cdb53d0153a4645109be216c12247b8e4a8e0228fb0b572b94f90e70c4dc987373f615c838990a910970bcd0d2c31d70f6310b90fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
